import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'hsla(23, 91.90%, 29.53%, 1.00)',
        secondary: '#FDF8F3',
        text: '#333',
        background: 'white',
      },
      fontFamily: {
        gilda: ['Gilda Display', 'serif'],
        hanken: ['Hanken Grotesk', 'sans-serif'],
      },
    },
  },
  safelist: [
    'w-full',
    'h-full',
    'min-h-[400px]',
    'min-h-[500px]',
    'fixed',
    'bottom-5',
    'right-5',
    'w-[350px]',
    'h-[500px]',
    'z-50',
    'shadow-lg',
    'rounded-xl',
    'bg-white',
    'flex',
    'flex-col',
    'justify-center',
    'space-y-8',
    'text-2xl',
    'leading-tight',
    'font-extralight',
    'text-gray-700',
    'text-gray-800',
    'px-8',
    'py-4',
    'text-white',
    'text-lg',
    'tracking-widest',
    'transition-all',
    'duration-300',
    'ease-in-out',
    'transform',
    'hover:bg-primary/90',
    'hover:-translate-y-1',
    'bg-gray-300',
    'cursor-not-allowed',
    'items-start',
    'space-x-2',
    'mt-4',
    'w-4',
    'h-4',
    'rounded',
    'border-gray-300',
    'focus:ring-primary',
    'text-xs',
    'underline',
    'hover:text-primary',
    'opacity-100',
    'scale-100',
    'opacity-0',
    'scale-95',
    'border-b',
    'border-gray-100',
    'font-bold',
    'text-gray-900',
    'text-sm',
    'text-gray-500',
    'h-[calc(100%-8rem)]',
    'overflow-y-auto',
    'space-y-4',
    'justify-end',
    'justify-start',
    'max-w-[80%]',
    'border-t',
    'mt-auto',
    'items-center',
    'flex-1',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
  ],
  plugins: [],
};

export default config; 